// export const uri = 'http://localhost:5000/user'
// export const expenseuri = 'http://localhost:5000/expense'
// export const vivahshulk = 'http://localhost:5000/vivahshulk'
export const uri = 'https://puja-chanda-back.onrender.com/user'
export const expenseuri = 'https://puja-chanda-back.onrender.com/expense'
export const vivahshulk = 'https://puja-chanda-back.onrender.com/vivahshulk'